# errata'd weapon properties
# contains the list of all weapon properties

properties = [
    "**Adaptive (Bludgeoning) [Mastery].** A weapon has an alternate damage type shown in parenthesis after the adaptive property. You choose the normal and alternate damage type each time you make an attack.",
    "**Adaptive (Piercing) [Mastery].** A weapon has an alternate damage type shown in parenthesis after the adaptive property. You choose the normal and alternate damage type each time you make an attack.",
    "**Adaptive (Slashing) [Mastery].** A weapon has an alternate damage type shown in parenthesis after the adaptive property. You choose the normal and alternate damage type each time you make an attack.",
    "**Ammunition (Bows).** You can use a weapon that has the ammunition property to make a ranged attack only if you have ammunition to fire from the weapon. Each time you attack with the weapon, you expend one piece of ammunition. Drawing the ammunition from a quiver, case, or other container is part of the attack (you need a free hand to load a one-handed weapon). \n\nIf you use a weapon that has the ammunition property to make a melee attack, you treat the weapon as an improvised weapon.\n\nA bow uses arrows or any ammunition that says in its description that says it can be used in conjunction with a bow. At the end of the battle, you can recover half your expended ammunition by taking a minute to search the battlefield, except for ammunition stating it would be broken or destroyed after use.",
    "**Ammunition (Crossbows).** You can use a weapon that has the ammunition property to make a ranged attack only if you have ammunition to fire from the weapon. Each time you attack with the weapon, you expend one piece of ammunition. Drawing the ammunition from a quiver, case, or other container is part of the attack (you need a free hand to load a one-handed weapon). \n\nIf you use a weapon that has the ammunition property to make a melee attack, you treat the weapon as an improvised weapon.\n\nA crossbow uses crossbow bolts or any ammunition that says in its description that says it can be used in conjunction with a crossbow. At the end of the battle, you can recover half your expended ammunition by taking a minute to search the battlefield, except for ammunition stating it would be broken or destroyed after use.",
    "**Ammunition (Firearms).** You can use a weapon that has the ammunition property to make a ranged attack only if you have ammunition to fire from the weapon. Each time you attack with the weapon, you expend one piece of ammunition. Drawing the ammunition from a quiver, case, or other container is part of the attack (you need a free hand to load a one-handed weapon). \n\nIf you use a weapon that has the ammunition property to make a melee attack, you treat the weapon as an improvised weapon.\n\nA firearm uses bullets or any ammunition that says in its description that says it can be used in conjunction with a firearm. The ammunition of a firearm is destroyed upon use.",
    "**Ammunition (Slings).** You can use a weapon that has the ammunition property to make a ranged attack only if you have ammunition to fire from the weapon. Each time you attack with the weapon, you expend one piece of ammunition. Drawing the ammunition from a quiver, case, or other container is part of the attack (you need a free hand to load a one-handed weapon). \n\nIf you use a weapon that has the ammunition property to make a melee attack, you treat the weapon as an improvised weapon. A sling must be loaded to deal any damage when used in this way.\n\nA sling uses sling bullets or any ammunition that says in its description that says it can be used in conjunction with a sling. At the end of the battle, you can recover half your expended ammunition by taking a minute to search the battlefield, except for ammunition stating it would be broken or destroyed after use.",
    "**Backswing [Mastery].** You gain a +2 bonus to attack with this weapon for each attack made with it that has missed before the end of your turn.",
    "**Brutal [Mastery].** On a critical hit, you can add a weapon damage die after doubling the damage dice.",
    "**Cleave [Mastery].** Once per turn, if you hit a creature with a melee attack using this weapon, you can make an attack roll with the weapon against a second creature within 5 feet of the first that is also within your reach.",
    "**Finesse.** When making an attack with a finesse weapon, you use your choice of your Strength or Dexterity modifier for the attack and damage rolls. You must use the same modifier for both rolls.",
    "**Forceful [Mastery].** Attacks with a forceful weapon gain a cumulative +1 bonus to damage rolls for each hit made with it this turn.",
    "**Glove.** A glove weapon is worn on your hand or forearm, and you cannot be disarmed of it. You can hold objects, wield weapons, and cast spells with a hand fitted with a glove weapon, but you can only attack with the glove weapon if that hand is unoccupied. It takes an action to don or doff a glove weapon.",
    "**Heavy.** Where most weapons are considered tiny, heavy weapons are considered small, requiring greater effort to be wielded effectively. Wielders suffer disadvantage on attacks with heavy weapons if their Strength score is less than 13, and a 5 foot speed reduction if their Strength is less than 15. For small creatures, these penalties also apply if their Constitution score is less than 13 and 15 respectively. Tiny creatures cannot wield heavy weapons.",
    "**Hinder [Mastery].** If you hit a creature with this weapon, that creature has Disadvantage on its next attack roll before the start of your next turn.",
    "**Jousting [Mastery].** While mounted, you can wield the weapon in one hand.",
    "**Light.** When you take the Attack action on your turn and attack with a Light weapon, you can make one extra attack as a Bonus Action later on the same turn. That extra attack must be made with a different Light weapon, and you don’t add your ability modifier to the extra attack’s damage, unless that modifier is negative.\n\nFor example, if you take the Attack action on your turn and have a Shortsword in one hand and a Dagger in the other—each of which has the Light property—you can make one attack with each weapon, using your action and a Bonus Action, but you don’t add your Strength or Dexterity modifier to the damage roll of the Bonus Action, unless that modifier is negative.",
    "**Loading.** Because of the time required to load this weapon, you can fire only one piece of ammunition from it when you use an action, bonus action, or reaction to fire it, regardless of the number of attacks you can normally make.",
    "**Nick [Mastery].** When you make the extra attack of the Light property, you can make it as part of the Attack action, instead of as a Bonus Action. You can still make this extra attack only once per turn.",
    "**Propulsive [Mastery].** You add half your Strength modifier (rounded down), if positive, to damage rolls with a propulsive ranged weapon.",
    "**Push [Mastery].** If you hit a creature with this weapon, you can push the creature up to 10 feet straight away from yourself if it is Large or smaller. You can only do this twice per turn.",
    "**Range (5/15).** A weapon that can be used to make a ranged attack when thrown has a range shown in parentheses. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.",
    "**Range (10/30).** A weapon that can be used to make a ranged attack when thrown has a range shown in parentheses. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.",
    "**Range (20/60).** A weapon that can be used to make a ranged attack when thrown has a range shown in parentheses. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.",
    "**Range (40/120).** A weapon that can be used to make a ranged attack when thrown has a range shown in parentheses. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.",
    "**Range (20/80).** A weapon that can be used to make a ranged attack when firing ammunition has a range shown in parentheses. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.",
    "**Range (25/100).** A weapon that can be used to make a ranged attack when firing ammunition has a range shown in parentheses. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.",
    "**Range (30/120).** A weapon that can be used to make a ranged attack when firing ammunition has a range shown in parentheses. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.",
    "**Range (40/160).** A weapon that can be used to make a ranged attack when firing ammunition has a range shown in parentheses. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.",
    "**Range (80/320).** A weapon that can be used to make a ranged attack when firing ammunition has a range shown in parentheses. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.",
    "**Range (100/400).** A weapon that can be used to make a ranged attack when firing ammunition has a range shown in parentheses. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.",
    "**Range (150/600).** A weapon that can be used to make a ranged attack when firing ammunition has a range shown in parentheses. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.",
    "**Reach.** This weapon adds 5 feet to your reach when you attack with it. This property also determines your reach for opportunity attacks with a reach weapon.",
    "**Slow [Mastery].** If you hit a creature with this weapon and deal damage to the creature, you can reduce its Speed by 10 feet until the start of your next turn. If you hit the creature more than once with this property, the Speed reduction doesn’t exceed 10 feet.",
    "**Special (Bayonet).** A weapon with the special property has unusual rules governing its use:\n\n**Bayonet.** Can be fixed to or removed from a weapon with the loading property as an action, allowing melee attacks with that weapon to use that bayonet to attack instead of the normal improvised weapon attack while fixed to it. While the bayonet is not fixed onto another weapon, its properties are treated as that of a dagger.",
    "**Special (Net).** A weapon with the special property has unusual rules governing its use:\n\n**Net.** A Large or smaller creature hit by a net is restrained until it is freed. A net has no effect on creatures that are formless, or creatures that are Huge or larger. A creature can use its action to make a DC 10 Strength check, freeing itself or another creature within its reach on a success. Dealing 5 slashing damage to the net (AC 10) also frees the creature without harming it, ending the effect and destroying the net. When you use an action, bonus action, or reaction to attack with a net, you can make only one attack regardless of the number of attacks you can normally make.",
    "**Special (Weighted Gauntlet).** A weapon with the special property has unusual rules governing its use:\n\n**Weighted Gauntlet.** When you are wielding weighted gauntlets, and you are holding nothing else in both hands, you gain a +1 bonus to armor class.",
    "**Tradition.** When the weapon is wielded with a shield, both pieces of equipment are treated as unproficient.",
    "**Thrown.** If a weapon has the Thrown property, you can throw the weapon to make a ranged attack, and you can draw that weapon as part of the attack. If the weapon is a  melee weapon, you use the same ability modifier for that attack roll and damage roll that you would use for a melee attack with the weapon. For example, if you throw a handaxe, you use your Strength, but if you throw a Dagger, you can use either your Strength or your Dexterity, since the Dagger has the Finesse property.",
    "**Trip [Mastery].** If you hit a creature with this weapon, you can force the creature to make a Constitution saving throw with a DC equal to 8 + your Proficiency Bonus + the ability modifier used to make the attack roll. On a failed save, the creature has the Prone condition. You can only do this once per turn.",
    "**Two-Handed.** This weapon requires two hands to use. This property is relevant only when you attack with the weapon, not when you simply hold it.",
    "**Versatile.** This weapon can be used with one or two hands. The damage value shown in parentheses is the damage when the weapon is used wtih two hands to make a melee attack. Properties that accompany the damage value in parentheses are gained when the weapon is used with two hands to make a melee attack.",
    "**Versatile (1d8).** This weapon can be used with one or two hands. The damage value shown in parentheses is the damage when the weapon is used wtih two hands to make a melee attack. Properties that accompany the damage value in parentheses are gained when the weapon is used with two hands to make a melee attack.",
    "**Versatile(1d8, Reach).** This weapon can be used with one or two hands. The damage value shown in parentheses is the damage when the weapon is used wtih two hands to make a melee attack. Properties that accompany the damage value in parentheses are gained when the weapon is used with two hands to make a melee attack.\n\n**Reach.** This weapon adds 5 feet to your reach when you attack with it. This property also determines your reach for opportunity attacks with a reach weapon.",
    "**Versatile (1d8, Trip).** This weapon can be used with one or two hands. The damage value shown in parentheses is the damage when the weapon is used wtih two hands to make a melee attack. Properties that accompany the damage value in parentheses are gained when the weapon is used with two hands to make a melee attack.\n\n**Trip [Mastery].** If you hit a creature with this weapon, you can force the creature to make a Constitution saving throw with a DC equal to 8 + your Proficiency Bonus + the ability modifier used to make the attack roll. On a failed save, the creature has the Prone condition. You can only do this once per turn.",
    "**Versatile (1d10).** This weapon can be used with one or two hands. The damage value shown in parentheses is the damage when the weapon is used wtih two hands to make a melee attack. Properties that accompany the damage value in parentheses are gained when the weapon is used with two hands to make a melee attack.",
    "**Versatile(1d10, Reach).** This weapon can be used with one or two hands. The damage value shown in parentheses is the damage when the weapon is used wtih two hands to make a melee attack. Properties that accompany the damage value in parentheses are gained when the weapon is used with two hands to make a melee attack.\n\n**Reach.** This weapon adds 5 feet to your reach when you attack with it. This property also determines your reach for opportunity attacks with a reach weapon.",
]

def getProperty(argument):
    returnProperty = ""
    for property in properties:
        substring = property[2:property.find(".**")] #removes wrapping for markdown bold
        if " ["  in substring: # removes everything following bracket for Mastery properties
            substring = substring[:substring.find(" [")]
        if argument.casefold() == substring.casefold(): #if argument is found in list, then return property as is
            returnProperty = property
    return returnProperty

def propertyList():
    returnList = []
    
    for prop in properties:
        substring = prop[2:prop.find(".**")] #removes wrapping for markdown bold
        if " [" in substring: # removes everything following bracket for Mastery properties
            substring = substring[:substring.find(" [")]
        returnList.append(substring) #adds only the name of the property to the array
    return returnList